# Generated by Django 3.2.18 on 2023-03-11 13:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list', '0002_auto_20230311_1150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List_Item',
            new_name='Entry',
        ),
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
