# Generated by Django 3.2.18 on 2023-03-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20230320_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.CharField(choices=[('a', 'Fresh'), ('b', 'Dairy'), ('c', 'Frozen'), ('d', 'Bakery'), ('e', 'Dry Ingredients'), ('f', 'Household'), ('g', 'Pet'), ('h', 'Personal Care'), ('i', 'Treats'), ('j', 'Alcohol')], default='Fresh', max_length=20),
        ),
        migrations.AlterField(
            model_name='entry',
            name='quantity',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='1'),
        ),
    ]
