# Generated by Django 3.2.18 on 2023-04-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20230324_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='item_name',
            field=models.CharField(max_length=60),
        ),
    ]
